labels:
  - name: "ğŸ› Typ: BÅ‚Ä…d"
    color: e80c0c
    description: CoÅ› nie dziaÅ‚a zgodnie z oczekiwaniami.

  - name: "â­ Typ: Usprawnienie"
    color: 54b2ff
    description: Sugestia usprawnienia istniejÄ…cej funkcji.

  - name: "ğŸš€ Typ: Funkcja"
    color: 54b2ff
    description: Sugestia nowej funkcji.

  - name: "ğŸ“‚ Typ: BezpieczeÅ„stwo"
    color: fbff00
    description: Problem lub usprawnienie zwiÄ…zane z kwestiÄ… bezpieczeÅ„stwa.

  - name: "ğŸ’« Status: Oczekuje na przeglÄ…d"
    color: 24d15d
    description: ZgÅ‚oszenie oczekuje na przeglÄ…d.

  - name: "ğŸ“œ Status: W trakcie pracy"
    color: 07b340
    description: Obecnie pracujemy nad tym.

  - name: "ğŸ’¾ Status: Oczekuje"
    color: 38C968
    description: Oczekuje na coÅ› innego, aby byÅ‚o gotowe.

  - name: "ğŸ“¦ Status: PrzestarzaÅ‚e"
    color: 66b38a
    description: Brak aktywnoÅ›ci przez jakiÅ› czas.

  - name: "ğŸª Duplikat"
    color: EB862D
    description: Duplikat innego zgÅ‚oszenia.

  - name: "âŒ NieprawidÅ‚owe"
    color: faef50
    description: To zgÅ‚oszenie wydaje siÄ™ nieprawidÅ‚owe.

  - name: "ğŸ”´ Priorytet: Wysoki +"
    color: ff008c
    description: ZgÅ‚oszenie wysokiego priorytetu.

  - name: "ğŸŸ¢ Priorytet: Niski -"
    color: 690a34
    description: ZgÅ‚oszenie niskiego priorytetu.

  - name: "ğŸ’¾ Typ: Dokumentacja"
    color: 2fbceb
    description: Problem/zmiana zwiÄ…zana z dokumentacjÄ….

  - name: "âš« Nie zostanie naprawione"
    color: C8D9E6
    description: ZgÅ‚oszony problem dziaÅ‚a zgodnie z zamierzeniami.
