repozytorium:
etykiety:
  - nazwa: "ğŸ› Typ: BÅ‚Ä…d"
    kolor: e80c0c
    opis: CoÅ› nie dziaÅ‚a zgodnie z oczekiwaniami.

  - nazwa: "â­ Typ: Usprawnienie"
    kolor: 54b2ff
    opis: Sugestia usprawnienia istniejÄ…cej funkcji.

  - nazwa: "ğŸš€ Typ: Funkcja"
    kolor: 54b2ff
    opis: Sugestia nowej funkcji.

  - nazwa: "ğŸ“‚ Typ: BezpieczeÅ„stwo"
    kolor: fbff00
    opis: Problem lub usprawnienie zwiÄ…zane z kwestiÄ… bezpieczeÅ„stwa.

  - nazwa: "ğŸ’« Status: Oczekuje na przeglÄ…d"
    kolor: 24d15d
    opis: ZgÅ‚oszenie oczekuje na przeglÄ…d.

  - nazwa: "ğŸ“œ Status: W trakcie pracy"
    kolor: 07b340
    opis: Obecnie pracujemy nad tym.

  - nazwa: "ğŸ’¾ Status: Oczekuje"
    kolor: 38C968
    opis: Oczekuje na coÅ› innego, aby byÅ‚o gotowe.

  - nazwa: "ğŸ“¦ Status: PrzestarzaÅ‚e"
    kolor: 66b38a
    opis: Brak aktywnoÅ›ci przez jakiÅ› czas.

  - nazwa: "ğŸª Duplikat"
    kolor: EB862D
    opis: Duplikat innego zgÅ‚oszenia.

  - nazwa: "âŒ NieprawidÅ‚owe"
    kolor: faef50
    opis: To zgÅ‚oszenie wydaje siÄ™ nieprawidÅ‚owe.

  - nazwa: "ğŸ”´ Priorytet: Wysoki +"
    kolor: ff008c
    opis: ZgÅ‚oszenie wysokiego priorytetu.

  - nazwa: "ğŸŸ¢ Priorytet: Niski -"
    kolor: 690a34
    opis: ZgÅ‚oszenie niskiego priorytetu.

  - nazwa: "ğŸ’¾ Typ: Dokumentacja"
    kolor: 2fbceb
    opis: Problem/zmiana zwiÄ…zana z dokumentacjÄ….

  - nazwa: "âš« Nie zostanie naprawione"
    kolor: C8D9E6
    opis: ZgÅ‚oszony problem dziaÅ‚a zgodnie z zamierzeniami.
